### ISSUE TITLE
Typo "dotner-bot"

### ISSUE THREAD

**Issue by PathogenDavid** [dotnet/brand#17]
On page 29 of [dotnet-brand-guidelines.pdf](https://github.com/dotnet/brand/blob/2e1ed6b476bc4ce4833fabdd0ad813101c77e417/dotnet-brand-guidelines.pdf) there's a typo: "the previous versions of the **dotner-bot** can still be used"

![image](https://user-images.githubusercontent.com/278957/91777107-91bdd800-ebb4-11ea-8e86-3cde16e5adaa.png)

--------------------

Also this is a bit pedantic, but on page 6, "principles.." is that supposed to be an ellipsis?

![image](https://user-images.githubusercontent.com/278957/91777128-a26e4e00-ebb4-11ea-907f-af6d448d90c8.png)

**Comment by BethMassi** [comment]
Nice catch. I will fix it!
