### ISSUE TITLE
dotnet-logo.png should be losslessly compressed

### ISSUE THREAD

**Issue by stamminator** [dotnet/brand#2]
Running dotnet-logo.png through some lossless compression algorithms using the PNGGauntlet Windows app produced a full-quality version at 1.66KB, less than half the size. Consider using a compressed version.

**Comment by BethMassi** [comment]
@kawilkin can you have a look?

**Comment by kawilkin** [comment]
@BethMassi Sure thing!

**Comment by kawilkin** [comment]
The dotnet-logo.png file has been updated to a compressed version.
