### ISSUE TITLE
Minimum logo size request exception

### ISSUE THREAD

**Issue by lostsatellites** [dotnet/brand#23]
@kkbrooks the .NET logo is used in GitLab when presenting the option to create a new project from a template, but it's used at 32px and not the 36px mentioned in the guidelines. Would it be possible to have an exception to use it at 32px? Thanks!

![.NET logo in template](https://user-images.githubusercontent.com/1437078/179545253-77c1db7e-ea93-4d63-aa4c-6acdace8d635.png)

**Comment by kkbrooks** [comment]
@lostsatellites that brand guidelines don't extend to type of scenario where the logo or icon size is determined by a third-party application or UI pattern, but focuses more on marketing materials, swag, use is a logo grid on a website (like a "used by these companies" or "technologies we use" section), etc. 

cc @BethMassi @mairaw

**Comment by lostsatellites** [comment]
Thank you @kkbrooks!
