### ISSUE TITLE
Cannot install embedded fonts on macOS (presentation template)

### ISSUE THREAD

**Issue by mpetrinidev** [dotnet/brand#4]
I'm using Office 365 on my macOS and PowerPoint couldn't install the following embedded fonts:

![image](https://user-images.githubusercontent.com/24263209/82956541-627d4680-9f87-11ea-81e2-6efa9d0d3c66.png)

**Comment by kawilkin** [comment]
@mpetrinidev I'll investigate this. The template shouldn't be using Segoe so it hopefully won't affect it, but Segoe shouldn't be embedded in the first place. I'll let you know once the template has been updated in the repo.

**Comment by kawilkin** [comment]
@mpetrinidev The template has been updated and these fonts are no longer embedded in the file.
