### ISSUE TITLE
Large size of jetpack wallpaper is rendered incorrectly

### ISSUE THREAD

**Issue by reflectronic** [dotnet/brand#6]
If you look at the [large version](https://github.com/dotnet/brand/blob/master/dotnet-bot-illustrations/Wallpapers/6016x3384/jetpack-6016x3384.png) of the jetpack wallpaper, dotnet-bot isn't looking too good (easier to see when comparing to the [smaller version](https://github.com/dotnet/brand/blob/master/dotnet-bot-illustrations/Wallpapers/1920x1080/jetpack-1920x1080.png)). All of the elements seem to be misaligned or warped.

**Comment by kawilkin** [comment]
Thanks for pointing that out! I'll take a look at the original files and make the fixes.

**Comment by kawilkin** [comment]
@reflectronic the file has been fixed and replaced!
